tasks:
  - init: |
      make all

vscode:
  extensions:
    - golang.go

gitConfig:
  alias.st: status
  alias.l: log --graph --pretty=default
  alias.lola: log --graph --oneline --all
  alias.fp: fetch --prune
