tasks:
  - init: |
      sudo cp docker/known_hosts /etc/ssh/ssh_known_hosts
      make all
  - name: vscode settings
    init: |
      mkdir -p "$PWD/.vscode";
      cat << 'EOF' > "$PWD/.vscode/settings.json"
        {
          "terminal.integrated.fontFamily": "Monospace",
          "terminal.integrated.fontSize": 14,
          "window.zoomLevel": 1
        }
      EOF
      exit

vscode:
  extensions:
    - golang.go

gitConfig:
  alias.st: status
  alias.l: log --graph --pretty=default
  alias.lola: log --graph --oneline --all
  alias.fp: fetch --prune
