tasks:
  - init: |
      sudo cp docker/known_hosts /etc/ssh/ssh_known_hosts

      curl -L https://github.com/gimlet-io/gimlet-cli/releases/download/v0.9.7/gimlet-$(uname)-$(uname -m) -o gimlet
      chmod +x gimlet
      sudo mv ./gimlet /usr/local/bin/gimlet
      gimlet --version

      cat << EOF > ~/.gimlet/config
      export GIMLET_SERVER=http://127.0.0.1:8888
      EOF

      make all
  - name: vscode settings
    init: |
      mkdir -p "$PWD/.vscode";
      cat << 'EOF' > "$PWD/.vscode/settings.json"
        {
          "terminal.integrated.fontFamily": "Monospace",
          "terminal.integrated.fontSize": 14,
          "window.zoomLevel": 1
        }
      EOF
      exit

vscode:
  extensions:
    - golang.go

gitConfig:
  alias.st: status
  alias.l: log --graph --pretty=default
  alias.lola: log --graph --oneline --all
  alias.fp: fetch --prune
