name: publish

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Checkout main
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        fetch-depth: 5

    - id: get_version
      uses: battila7/get-version-action@v2

    - name: Version is sha or tag
      id: sha_or_tag
      run: |
        echo "::set-output name=version::$VERSION"
        if [[ $VERSION == refs/heads/* ]]
        then
            echo "::set-output name=version::$GITHUB_SHA"
        fi
      env:
        VERSION: ${{ steps.get_version.outputs.version-without-v }}

    - name: Dist
      run: make dist
      env:
        VERSION: ${{ steps.sha_or_tag.outputs.version }}

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload release binaries
      uses: alexellis/upload-assets@0.2.2
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        asset_paths: '["./bin/gimletd*"]'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.PAT }} # `PAT` is a secret that contains your Personal Access Token with `write:packages` scope

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: docker/Dockerfile
        platforms: linux/amd64
        push: true
        tags: |
          ghcr.io/${{ github.repository }}:${{ steps.sha_or_tag.outputs.version }}
