name: Tip
on:
  push:
    branches:
      - 'main'

jobs:
  build:
    name: Tip
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14.7

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
      with:
        fetch-depth: 5

    - id: get_version
      uses: battila7/get-version-action@v2

    - name: Version is sha or tag
      id: sha_or_tag
      run: |
        if [[ $VERSION == refs/heads/* ]]
        then
            echo "::set-output name=version::$GITHUB_SHA"
        fi
      env:
        VERSION: ${{ steps.get_version.outputs.version-without-v }}

    - name: Test
      run: make test

    - name: Dist
      run: make dist
      env:
        VERSION: ${{ steps.sha_or_tag.outputs.version }}

    - name: tip
      uses: eine/tip@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        rm: true
        files: |
          bin/*

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.PAT }} # `PAT` is a secret that contains your Personal Access Token with `write:packages` scope

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64
        push: true
        tags: |
          ghcr.io/${{ github.repository }}:latest
